### ISSUE TITLE
Engine not working, cannot find a valid glfw library

### ISSUE THREAD

**Issue by Je06jm** [Je06jm/PyEngine#4]
After downloading the master branch, installing all the requirements, and renaming Natives to natives, the example won't run. When the example is ran on the console, it returns a error message saying that the engine could not load a valid glfw library

**Comment by Graystevo** [comment]
Is it supposed to be, "Natives to native" or "Native to natives"?

**Comment by Graystevo** [comment]
C:\Users\18stevegraw\Desktop\pyengine>game.py
Traceback (most recent call last):
  File "C:\Users\18stevegraw\Desktop\pyengine\game.py", line 35, in <module>
    w = win.create(winSet)
  File "C:\Users\18stevegraw\Desktop\pyengine\PyEngine\window.py", line 45, in create
    raise GLFWError("Could not create glfw window!")
PyEngine.natives.glfw3.GLFWError: Could not create glfw window!
